-keep public class * implements com.thomas.base.mvp.IBaseMvpModel
-keep public class * implements com.thomas.base.mvp.IBaseMvpView
-keep public class * extends com.thomas.base.mvp.BaseMvpPresenter
-keep public class * implements com.thomas.base.component.ModuleConfig